wandb_version: 1

activation:
  desc: null
  value: ReLU
epochs:
  desc: null
  value: 50000
lr:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708646080.942179
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.13
      5: 0.15.9
      8:
      - 5
